name: test

on:
  push:
    branch:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 pytest-cov
        pip install -r tests/requirements.txt
    - name: Format with black
      run: |
        black --check flask_docs examples tests
    - name: Lint with flake8
      run: |
        flake8 flask_docs tests examples
    - name: Test with pytest
      run: |
        pytest --cov=flask_docs --cov-report=xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
